/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jesus Romero
 */
import static com.mycompany.tareaprogramacion.TareaProgramacion2.notificar;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

class Estudiante {
    String nombre;
    String sede;

    public Estudiante(String nombre, String sede) {
        this.nombre = nombre;
        this.sede = sede;
    }

    public String getNombre() {
        return nombre;
    }

    public String getSede() {
        return sede;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Estudiante that = (Estudiante) o;

        return nombre.equals(that.nombre);
    }

    @Override
    public int hashCode() {
        return nombre.hashCode();
    }
}

public class Tarea2 extends javax.swing.JFrame {
     Set<Estudiante> listaA = new HashSet<>();
     Set<Estudiante> listaB = new HashSet<>();
     Set<Estudiante> listaC = new HashSet<>();
     Boolean ValidarEstudiante = false;
     String ResultadoMensaje = "";
        
    public static void notificar(Set<Estudiante> listaA, Set<Estudiante> listaB, Set<Estudiante> listaC) {
        // Filtrar solo los estudiantes de la sede de Málaga
        Set<Estudiante> malagaA = filtrarPorSede(listaA, "Malaga");
        Set<Estudiante> malagaB = filtrarPorSede(listaB, "Malaga");
        Set<Estudiante> malagaC = filtrarPorSede(listaC, "Malaga");

        // Usamos un Set para asegurarnos de que cada estudiante reciba solo un email
        Set<Estudiante> estudiantesNotificados = new HashSet<>();

        // Notificamos a los estudiantes en la lista C primero (Matemáticas y Francés)
        for (Estudiante estudiante : malagaC) {
            if (!estudiantesNotificados.contains(estudiante)) {
                enviarEmail(estudiante, "incidenciaMatematicasYFrances");
                estudiantesNotificados.add(estudiante);
            }
        }

        // Notificamos a los estudiantes en la lista A (Matemáticas)
        for (Estudiante estudiante : malagaA) {
            if (!estudiantesNotificados.contains(estudiante)) {
                enviarEmail(estudiante, "incidenciaMatematicas");
                estudiantesNotificados.add(estudiante);
            }
        }

        // Notificamos a los estudiantes en la lista B (Francés)
        for (Estudiante estudiante : malagaB) {
            if (!estudiantesNotificados.contains(estudiante)) {
                enviarEmail(estudiante, "incidenciaFrances");
                estudiantesNotificados.add(estudiante);
            }
        }
    }

    private static Set<Estudiante> filtrarPorSede(Set<Estudiante> lista, String sede) {
        Set<Estudiante> resultado = new HashSet<>();
        for (Estudiante estudiante : lista) {
            if (estudiante.getSede().equalsIgnoreCase(sede)) {
                resultado.add(estudiante);
            }
        }
        return resultado;
    }

    private static void enviarEmail(Estudiante estudiante, String tipoIncidencia) {
        // Aquí iría el código para enviar el email
        System.out.println("Enviando email a " + estudiante.getNombre() + " por " + tipoIncidencia);
        JOptionPane.showMessageDialog(null, "Enviando email a " + estudiante.getNombre() + " por " + tipoIncidencia, "Correo Enviado", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Creates new form Tarea2
     */
    public Tarea2() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSede = new javax.swing.JTextField();
        jTextFieldAlumno = new javax.swing.JTextField();
        jComboBoxSede = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCorreo = new javax.swing.JButton();
        jButtonAddAlumno = new javax.swing.JButton();
        jLabelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea 2");

        jPanel1.setBackground(new java.awt.Color(69, 182, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tarea 2");

        jTextFieldAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlumnoActionPerformed(evt);
            }
        });

        jComboBoxSede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista A", "Lista B", "Lista C" }));
        jComboBoxSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSedeActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insertar Alumno");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Insertar Sede");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Insertar Lista");

        jButtonCorreo.setBackground(new java.awt.Color(24, 75, 200));
        jButtonCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCorreo.setText("Enviar Correos");
        jButtonCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarCorreos(evt);
            }
        });

        jButtonAddAlumno.setBackground(new java.awt.Color(116, 24, 200));
        jButtonAddAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddAlumno.setText("Añadir otro Alumno");
        jButtonAddAlumno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAlumno(evt);
            }
        });

        jLabelResultado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResultado.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 132, Short.MAX_VALUE)
                .addComponent(jButtonAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldSede, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxSede, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabelResultado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jTextFieldSede, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSede, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelResultado)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSedeActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBoxSede.getSelectedItem();
    
        // Obtener el índice del ítem seleccionado
        int selectedIndex = jComboBoxSede.getSelectedIndex();
    
        // Mostrar el ítem seleccionado en la consola o utilizarlo como desees
        System.out.println("Ítem seleccionado: " + selectedItem);
        System.out.println("Índice seleccionado: " + selectedIndex);
    }//GEN-LAST:event_jComboBoxSedeActionPerformed

    private void jTextFieldAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlumnoActionPerformed

    private void AddAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAlumno
        
        
        String selectedItem = (String) jComboBoxSede.getSelectedItem();
        int selectedIndex = jComboBoxSede.getSelectedIndex();
        String textoAlumno = jTextFieldAlumno.getText();
        String textoSede = jTextFieldSede.getText();
        
        switch(selectedIndex){
            case 0:
                this.listaA.add(new Estudiante(textoAlumno, textoSede));
            break;
            case 1:
                this.listaB.add(new Estudiante(textoAlumno, textoSede));
            break;
            case 2:
                this.listaC.add(new Estudiante(textoAlumno, textoSede));
            break;
            default:
                this.listaA.add(new Estudiante(textoAlumno, textoSede));
            break;
        }
        jTextFieldAlumno.setText("");
        jTextFieldSede.setText("");
        this.ValidarEstudiante = true;
        jLabelResultado.setText("Alumno Insertado Correctamente");
        // Mostrar el ítem seleccionado en la consola o utilizarlo como desees
        System.out.println("Ítem seleccionado: " + selectedItem);
        System.out.println("Índice seleccionado: " + selectedIndex);
        
        
    }//GEN-LAST:event_AddAlumno

    private void EnviarCorreos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarCorreos
        // TODO add your handling code here:
        if (this.ValidarEstudiante == false){
            jLabelResultado.setText("Tiene Insertar un Alumno");
        }else {
            this.notificar(this.listaA,this.listaB,this.listaC);
        }
    }//GEN-LAST:event_EnviarCorreos

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarea2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarea2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarea2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarea2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarea2().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAlumno;
    private javax.swing.JButton jButtonCorreo;
    private javax.swing.JComboBox<String> jComboBoxSede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAlumno;
    private javax.swing.JTextField jTextFieldSede;
    // End of variables declaration//GEN-END:variables
}
